//Product list
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

//Product details
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

// Create product
export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

// Update product
export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

// Delete product
export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

// Check token valitadion
export const CHECK_TOKEN_VALIDATION_REQUEST = "CHECK_TOKEN_VALIDATION_REQUEST";
export const CHECK_TOKEN_VALIDATION_SUCCESS = "CHECK_TOKEN_VALIDATION_SUCCESS";
export const CHECK_TOKEN_VALIDATION_FAIL = "CHECK_TOKEN_VALIDATION_FAIL";
export const CHECK_TOKEN_VALIDATION_RESET = "CHECK_TOKEN_VALIDATION_RESET";

// create card
export const CARD_CREATE_REQUEST = "CARD_CREATE_REQUEST";
export const CARD_CREATE_SUCCESS = "CARD_CREATE_SUCCESS";
export const CARD_CREATE_FAIL = "CARD_CREATE_FAIL";
export const CARD_CREATE_RESET = "CARD_CREATE_RESET";

// Charge card
export const CARD_CHARGE_REQUEST = "CARD_CHANGE_REQUEST";
export const CARD_CHARGE_SUCCESS = "CARD_CHANGE_SUCCESS";
export const CARD_CHARGE_FAIL = "CARD_CHANGE_FAIL";
export const CARD_CHARGE_RESET = "CARD_CHANGE_RESET";

//Saved cards list
export const CARD_LIST_REQUEST = "CARD_LIST_REQUEST";
export const CARD_LIST_SUCCESS = "CARD_LIST_SUCCESS";
export const CARD_LIST_FAIL = "CARD_LIST_FAIL";

// update card
export const CARD_UPDATE_REQUEST = "CARD_UPDATE_REQUEST";
export const CARD_UPDATE_SUCCESS = "CARD_UPDATE_SUCCESS";
export const CARD_UPDATE_FAIL = "CARD_UPDATE_FAIL";
export const CARD_UPDATE_RESET = "CARD_UPDATE_RESET";

//Delete saved card
export const CARD_DELETE_REQUEST = "CARD_DELETE_REQUEST";
export const CARD_DELETE_SUCCESS = "CARD_DELETE_SUCCESS";
export const CARD_DELETE_FAIL = "CARD_DELETE_FAIL";
export const CARD_DELETE_RESET = "CARD_DELETE_RESET";

// User login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

// User register- signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

// User details
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

// Update user
export const USER_UPDATE_DETAILS_REQUEST = "USER_UPDATE_DETAILS_REQUEST";
export const USER_UPDATE_DETAILS_SUCCESS = "USER_UPDATE_DETAILS_SUCCESS";
export const USER_UPDATE_DETAILS_FAIL = "USER_UPDATE_DETAILS_FAIL";
export const USER_UPDATE_DETAILS_RESET = "USER_UPDATE_DETAILS_RESET";

// delete user
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";

//User all address
export const USER_ADDRESS_LIST_REQUEST = "USER_ADDRESS_LIST_REQUEST";
export const USER_ADDRESS_LIST_SUCCESS = "USER_ADDRESS_LIST_SUCCESS";
export const USER_ADDRESS_LIST_FAIL = "USER_ADDRESS_LIST_FAIL";

//User address details
export const USER_ADDRESS_DETAILS_REQUEST = "USER_ADDRESS_DETAILS_REQUEST";
export const USER_ADDRESS_DETAILS_SUCCESS = "USER_ADDRESS_DETAILS_SUCCESS";
export const USER_ADDRESS_DETAILS_FAIL = "USER_ADDRESS_DETAILS_FAIL";
export const USER_ADDRESS_DETAILS_RESET = "USER_ADDRESS_DETAILS_RESET";

//User address create
export const USER_ADDRESS_CREATE_REQUEST = "USER_ADDRESS_CREATE_REQUEST";
export const USER_ADDRESS_CREATE_SUCCESS = "USER_ADDRESS_CREATE_SUCCESS";
export const USER_ADDRESS_CREATE_FAIL = "USER_ADDRESS_CREATE_FAIL";
export const USER_ADDRESS_CREATE_RESET = "USER_ADDRESS_CREATE_RESET";

//User address update
export const USER_ADDRESS_UPDATE_REQUEST = "USER_ADDRESS_UPDATE_REQUEST";
export const USER_ADDRESS_UPDATE_SUCCESS = "USER_ADDRESS_UPDATE_SUCCESS";
export const USER_ADDRESS_UPDATE_FAIL = "USER_ADDRESS_UPDATE_FAIL";
export const USER_ADDRESS_UPDATE_RESET = "USER_ADDRESS_UPDATE_RESET";

//User address delete
export const USER_ADDRESS_DELETE_REQUEST = "USER_ADDRESS_DELETE_REQUEST";
export const USER_ADDRESS_DELETE_SUCCESS = "USER_ADDRESS_DELETE_SUCCESS";
export const USER_ADDRESS_DELETE_FAIL = "USER_ADDRESS_DELETE_FAIL";
export const USER_ADDRESS_DELETE_RESET = "USER_ADDRESS_DELETE_RESET";

//all orders list
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

//change order status
export const ORDER_CHANGE_STATUS_REQUEST = "ORDER_CHANGE_STATUS_REQUEST";
export const ORDER_CHANGE_STATUS_SUCCESS = "ORDER_CHANGE_STATUS_SUCCESS";
export const ORDER_CHANGE_STATUS_FAIL = "ORDER_CHANGE_STATUS_FAIL";
export const ORDER_CHANGE_STATUS_RESET = "ORDER_CHANGE_STATUS_RESET";